// Code generated by MockGen. DO NOT EDIT.
// Source: dynamo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dynamodb "github.com/aws/aws-sdk-go-v2/service/dynamodb"
	gomock "github.com/golang/mock/gomock"
)

// MockDynamoDbClientInterface is a mock of DynamoDbClientInterface interface.
type MockDynamoDbClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDynamoDbClientInterfaceMockRecorder
}

// MockDynamoDbClientInterfaceMockRecorder is the mock recorder for MockDynamoDbClientInterface.
type MockDynamoDbClientInterfaceMockRecorder struct {
	mock *MockDynamoDbClientInterface
}

// NewMockDynamoDbClientInterface creates a new mock instance.
func NewMockDynamoDbClientInterface(ctrl *gomock.Controller) *MockDynamoDbClientInterface {
	mock := &MockDynamoDbClientInterface{ctrl: ctrl}
	mock.recorder = &MockDynamoDbClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamoDbClientInterface) EXPECT() *MockDynamoDbClientInterfaceMockRecorder {
	return m.recorder
}

// PutItem mocks base method.
func (m *MockDynamoDbClientInterface) PutItem(ctx context.Context, params *dynamodb.PutItemInput, optFns ...func(*dynamodb.Options)) (*dynamodb.PutItemOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutItem", varargs...)
	ret0, _ := ret[0].(*dynamodb.PutItemOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutItem indicates an expected call of PutItem.
func (mr *MockDynamoDbClientInterfaceMockRecorder) PutItem(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutItem", reflect.TypeOf((*MockDynamoDbClientInterface)(nil).PutItem), varargs...)
}
